# Generated by Django 2.2.8 on 2020-04-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('weight', models.IntegerField(default=-1)),
                ('height', models.IntegerField(default=-1)),
                ('gender', models.IntegerField(default=-1)),
                ('goal', models.DecimalField(decimal_places=10, default=-1.0, max_digits=15)),
                ('lifestyle', models.DecimalField(decimal_places=10, default=-1.0, max_digits=15)),
                ('vegetarian', models.BooleanField(default=True)),
                ('age', models.IntegerField(default=-1)),
                ('calories_intake', models.IntegerField(default=-1)),
            ],
        ),
    ]
