# Generated by Django 3.0.3 on 2020-02-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
    ]
