# Generated by Django 3.0.3 on 2020-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20200224_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='users',
            name='goal',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='users',
            name='height',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='users',
            name='lifestyle',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='users',
            name='vegetarian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='weight',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
