# Generated by Django 3.0.3 on 2020-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200224_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='lifestyle',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='vegetarian',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
