# Generated by Django 3.0.3 on 2020-02-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
