# Generated by Django 3.0.3 on 2020-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20200225_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='users',
            name='calories_intake',
            field=models.IntegerField(default=-1),
        ),
    ]
