# Generated by Django 3.0.3 on 2020-02-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20200225_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='goal',
            field=models.DecimalField(decimal_places=5, default=-1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='users',
            name='lifestyle',
            field=models.DecimalField(decimal_places=5, default=-1.0, max_digits=5),
        ),
    ]
